name: Build & Push Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'       # only trigger when backend code changes
    workflow_dispatch:     # ← manual trigger from the Actions tab

permissions:
  contents: read       # you only need to read the repo
  packages: write      # we need to publish to GHCR

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile 
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/backend:latest